[environment]
env = "dev"
version = "0.1.0"

[commands]
hello = "echo 'Hello, world!'"
goodbye = "echo 'Goodbye, world!'"
combo = ["hello", "goodbye"]
build-cover = "go test -coverprofile=./out/coverage.out ./..."
build-cover-html = "go tool cover -html=./out/coverage.out -o ./out/coverage.html"
cover = ["build-cover", "build-cover-html"]
