[commands]
hello = "echo 'Hello, world!'"
goodbye = "echo 'Goodbye, world!'"
list-cmds = "go run . list"
build-win = "go build -o gr.exe ."
combo = ["hello", "goodbye"]
inf = ["inf"]

[commands.other]
command = "echo"
args = ["hello, world"]